# development
FROM node:15.11.0-alpine AS develop
WORKDIR /app
COPY package.json yarn.lock ./
RUN yarn install --frozen-lockfile

# builder
FROM node:15.11.0-alpine AS builder
WORKDIR /app
COPY . .
COPY --from=develop /app/node_modules ./node_modules
RUN yarn build

# production
FROM node:15.11.0-alpine AS runner
WORKDIR /app

ENV NODE_ENV production

COPY --from=builder /app/public ./public
COPY --from=builder /app/.next ./.next
COPY --from=builder /app/node_modules ./node_modules

RUN addgroup -g 1001 -S nodejs
RUN adduser -S nextjs -u 1001
RUN chown -R nextjs:nodejs /app/.next
USER nextjs

EXPOSE 3000

CMD ["node_modules/.bin/next", "start"]
